### ISSUE TITLE
Broker never scales down

### ISSUE THREAD

**Issue by dynamiccast** [Nanocloud/nanocloud#275]
This PR introduced the bug: https://github.com/Nanocloud/nanocloud/pull/259

The broker never scales down because of the following error:

```
backend             | Unhandled rejection TypeError: Cannot read property 'length' of undefined
backend             |     at getSessions.then (/opt/back/api/models/Machine.js:155:23)
backend             |     at tryCatcher (/opt/back/node_modules/bluebird/js/release/util.js:16:23)
backend             |     at Promise._settlePromiseFromHandler (/opt/back/node_modules/bluebird/js/release/promise.js:510:31)
backend             |     at Promise._settlePromise (/opt/back/node_modules/bluebird/js/release/promise.js:567:18)
backend             |     at Promise._settlePromise0 (/opt/back/node_modules/bluebird/js/release/promise.js:612:10)
backend             |     at Promise._settlePromises (/opt/back/node_modules/bluebird/js/release/promise.js:691:18)
backend             |     at Async._drainQueue (/opt/back/node_modules/bluebird/js/release/async.js:138:16)
backend             |     at Async._drainQueues (/opt/back/node_modules/bluebird/js/release/async.js:148:10)
backend             |     at Immediate.Async.drainQueues (/opt/back/node_modules/bluebird/js/release/async.js:17:14)
backend             |     at runCallback (timers.js:566:20)
backend             |     at tryOnImmediate (timers.js:546:5)
backend             |     at processImmediate [as _immediateCallback] (timers.js:525:5)
```

This is because the `catch` method returns undefined here : https://github.com/Nanocloud/nanocloud/pull/259/commits/9a61cca17513f1191a83b5437d4613485cf6f011#diff-ba475598a42e65f8dcf8f79521046598R138
This leads to `sessions` being undefined but assumed to be an array here https://github.com/Nanocloud/nanocloud/blob/master/api/models/Machine.js#L150

**Comment by dynamiccast** [comment]
Fixed in #277
