### ISSUE TITLE
AWS: broker never scales down

### ISSUE THREAD

**Issue by dynamiccast** [Nanocloud/nanocloud#50]
Even though `endDate` seems to be valid, no machines are ever terminated on AWS.

**Comment by dynamiccast** [comment]
After `sessionDuration` the following error appears in logs:

```
backend             | Unhandled rejection TypeError: Cannot read property 'length' of undefined
backend             |     at request.getAsync.then.err (/opt/back/api/models/Machine.js:102:17)
backend             |     at tryCatcher (/opt/back/node_modules/bluebird/js/release/util.js:16:23)
backend             |     at Promise._settlePromiseFromHandler (/opt/back/node_modules/bluebird/js/release/promise.js:504:31)
backend             |     at Promise._settlePromise (/opt/back/node_modules/bluebird/js/release/promise.js:561:18)
backend             |     at Promise._settlePromise0 (/opt/back/node_modules/bluebird/js/release/promise.js:606:10)
backend             |     at Promise._settlePromises (/opt/back/node_modules/bluebird/js/release/promise.js:685:18)
backend             |     at Promise._fulfill (/opt/back/node_modules/bluebird/js/release/promise.js:630:18)
backend             |     at Request._callback (/opt/back/node_modules/bluebird/js/release/nodeback.js:42:21)
backend             |     at Request.self.callback (/opt/back/node_modules/request/request.js:187:22)
backend             |     at emitTwo (events.js:106:13)
backend             |     at Request.emit (events.js:191:7)
backend             |     at Request.<anonymous> (/opt/back/node_modules/request/request.js:1044:10)
backend             |     at emitOne (events.js:96:13)
backend             |     at Request.emit (events.js:188:7)
backend             |     at IncomingMessage.<anonymous> (/opt/back/node_modules/request/request.js:965:12)
backend             |     at emitNone (events.js:91:20)
backend             |     at IncomingMessage.emit (events.js:185:7)
backend             |     at endReadableNT (_stream_readable.js:973:12)
backend             |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
backend             |     at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

I suspect `/sessions/` not to work on plaza. This would explain why it's working with the dummy driver in tests: Fake plaza is designed  so the test works.

**Comment by dynamiccast** [comment]
After further investigation.
Plaza is not called correctly in `api/model/Machine.js:88`. The proper URL would be :`/sessions/{username}`.
